# Generated by Django 5.0.6 on 2024-07-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, null=True, blank=True),
        ),
       
    ]
