# Generated by Django 5.0.6 on 2024-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_email_field'),
    ]

    operations = [
         migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
         migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='category',
        ),
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wealth_type',
        ),

    ]
