# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'aatravelapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aatravelapp
  pod 'GoogleSignIn'
  pod 'AppAuth'

  target 'aatravelappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aatravelappUITests' do
    # Pods for testing
  end

end
